// Mock data for Profinoks home page clone
// All content here is static and not loaded from any backend API.

export const sliderItems = [
  {
    id: 1,
    title: "",
    imageUrl: "/profinoks/hero/hero-1.jpg",
  },
  {
    id: 2,
    title: "",
    imageUrl: "/profinoks/hero/hero-2.jpg",
  },
  {
    id: 3,
    title: "",
    imageUrl: "/profinoks/hero/hero-3.jpg",
  },
  {
    id: 4,
    title: "",
    imageUrl: "/profinoks/hero/hero-4.jpg",
  },
  {
    id: 5,
    title: "",
    imageUrl: "/profinoks/hero/hero-5.jpg",
  },
];

export const productGroups = [
  { id: 1, title: "PİŞİRİCİLER", slug: "cookers", imageUrl: "/ormel/group-restaurant.png", description: "Gazlı ve elektrikli yer ocakları, devrilir tavalar, kuzine fırınlar ve ızgaralar." },
  { id: 2, title: "FIRINLAR", slug: "ovens", imageUrl: "/ormel/group-restaurant.png", description: "Gazlı pasta börek fırınları ve çeşitli endüstriyel fırınlar." },
  { id: 3, title: "BULAŞIK MAKİNELERİ", slug: "dishwashers", imageUrl: "/ormel/group-restaurant.png", description: "Endüstriyel bulaşık yıkama çözümleri." },
  { id: 4, title: "HAZIRLIK MAKİNELERİ", slug: "prep-machines", imageUrl: "/ormel/group-restaurant.png", description: "Mutfak hazırlık süreçleri için yardımcı ekipmanlar." },
  { id: 5, title: "İÇECEK MAKİNELERİ", slug: "beverage-machines", imageUrl: "/ormel/group-restaurant.png", description: "Çay, kahve ve soğuk içecek hazırlama makineleri." },
  { id: 6, title: "SELF SERVİS ÜNİTELERİ", slug: "self-service", imageUrl: "/ormel/group-restaurant.png", description: "Yemek dağıtım ve self servis hatları." },
  { id: 7, title: "AÇIK BÜFE SERVİS ÜNİTELERİ", slug: "buffet-service", imageUrl: "/ormel/group-restaurant.png", description: "Modern ve estetik açık büfe sunum çözümleri." },
  { id: 8, title: "BUZDOLAPLARI", slug: "refrigerators", imageUrl: "/ormel/group-restaurant.png", description: "Endüstriyel tip buzdolapları ve saklama üniteleri." },
  { id: 9, title: "SOĞUK ODALAR", slug: "cold-rooms", imageUrl: "/ormel/group-restaurant.png", description: "Panel tip soğuk oda ve depo çözümleri." },
  { id: 10, title: "TEZGAHLAR", slug: "workbenches", imageUrl: "/ormel/group-restaurant.png", description: "Çalışma, evyeli ve hazırlık tezgahları." },
  { id: 11, title: "İSTİF RAFLARI VE DEPOLAMA", slug: "storage", imageUrl: "/ormel/group-restaurant.png", description: "Mutfak ve depo için raf sistemleri." },
  { id: 12, title: "YER IZGARALARI & YAĞ AYIRICILAR", slug: "gratings", imageUrl: "/ormel/group-restaurant.png", description: "Drenaj kanalları ve yağ ayırıcı sistemler." },
  { id: 13, title: "DAVLUMBAZLAR", slug: "hoods", imageUrl: "/ormel/group-restaurant.png", description: "Havalandırma ve davlumbaz sistemleri." },
  { id: 14, title: "MUTFAK ARABALARI", slug: "trolleys", imageUrl: "/ormel/group-housekeeping.png", description: "Taşıma, servis ve toplama arabaları." },
  { id: 15, title: "YARDIMCI MUTFAK EKİPMANLARI", slug: "auxiliary", imageUrl: "/ormel/group-restaurant.png", description: "Tencere, tava ve küçük el aletleri." },
  { id: 16, title: "SETÜSTÜ OTEL EKİPMANLARI", slug: "tabletop", imageUrl: "/ormel/group-frontoffice.png", description: "Otel odası ve restoran setüstü ekipmanları." },
  { id: 17, title: "ÇAMAŞIRHANE EKİPMANLARI", slug: "laundry", imageUrl: "/ormel/group-housekeeping.png", description: "Endüstriyel çamaşır yıkama ve kurutma makineleri." },
];

export const contactInfo = {
  address: "Firuzköy Mah. Mezarlık Üstü Cad. No:13 34325 Avcılar İstanbul Türkiye",
  phone: ["+90 850 420 87 37", "+90 212 501 51 25"],
  fax: "+90 212 501 51 26",
  emails: ["info@profinoks.com.tr", "proje@profinoks.com.tr"],
  workingHours: "Pazartesi - Cuma: 08:30 - 18:30"
};

export const referenceLogos = [
  "/profinoks/references/20-artinox.webp",
  "/profinoks/references/Anadoluefes_logo.jpg",
  "/profinoks/references/Ashan_Logo_S_001.svg",
  "/profinoks/references/Coca-Cola_logo.svg",
  "/profinoks/references/LP10mangal-doener-logo.webp",
  "/profinoks/references/TMSF_logo.svg",
  "/profinoks/references/Trendyol_online.png",
  "/profinoks/references/akkolgruplogo.png",
  "/profinoks/references/anadoluısuzu.png",
  "/profinoks/references/aydın holding.png",
  "/profinoks/references/bybosnak.png",
  "/profinoks/references/cafe duo.jpeg",
  "/profinoks/references/chef bilal.jpg",
  "/profinoks/references/das-miracle-logo.png",
  "/profinoks/references/easycheespizza.jpeg",
  "/profinoks/references/elitcuplogo.webp",
  "/profinoks/references/etit mimarlık.png",
  "/profinoks/references/fabrika tantuni.jpg",
  "/profinoks/references/hereni döner.jpg",
  "/profinoks/references/hereni döner.png",
  "/profinoks/references/heybet döner.png",
  "/profinoks/references/images.png",
  "/profinoks/references/istek okulları.png",
  "/profinoks/references/kahve dünyası.webp",
  "/profinoks/references/karadeniz restaunt özbekistan.jpg",
  "/profinoks/references/leziz esnaf lokantası.png",
  "/profinoks/references/mahsun-usta.png",
  "/profinoks/references/meşhur bursa tulumbacısı.jpg",
  "/profinoks/references/multi pizza.png",
  "/profinoks/references/papamardin.jpeg",
  "/profinoks/references/piacafenorveç.jpeg",
  "/profinoks/references/png-transparent-a1-catering-logo-production-others.png",
  "/profinoks/references/soa.jpg",
  "/profinoks/references/sofra compas.png",
  "/profinoks/references/sofra.png",
  "/profinoks/references/tella kebap.jpg",
  "/profinoks/references/turkuaz catering.jpeg",
  "/profinoks/references/vem ilaç.jpeg",
  "/profinoks/references/İstanbul_Medeniyet_Üniversitesi_logo.svg",
];

export const testimonials = [
  {
    id: 1,
    person: "Thomas Müller",
    role: "Müller Gastronomie GmbH (Almanya)",
    quote: "Profinoks ile çalışmaya başladıktan sonra profesyonel mutfak ekipmanları konusundaki bakış açımız tamamen değişti. Ürünlerin malzeme kalitesi, işçilik detayları ve uzun ömürlü yapısı gerçekten güven veriyor. Satış öncesi danışmanlık süreci çok açıklayıcıydı, ihtiyaçlarımıza birebir çözüm sundular. Teslimat ve kurulum aşamasında da son derece düzenli ve titiz davrandılar.",
  },
  {
    id: 2,
    person: "Jean Dupont",
    role: "Hôtel Lumière (Fransa)",
    quote: "Otel mutfağımız için tercih ettiğimiz Profinoks ürünlerinden son derece memnunuz. Özellikle paslanmaz çelik kalitesi ve ergonomik tasarımlar günlük operasyonlarimizi ciddi anlamda kolaylaştırdı. Satış sonrası destek ekibi her sorumuza hızlıca dönüş sağladı. Bu kadar profesyonel ve çözüm odaklı bir firma ile çalışmak gerçekten büyük bir avantaj.",
  },
  {
    id: 3,
    person: "Luca Bianchi",
    role: "Bianchi Ristorante SRL (İtalya)",
    quote: "Profinoks, sadece ürün satan bir firma değil, aynı zamanda mutfak projelerinde gerçek bir çözüm ortağı. Restoranımız için yapılan keşif, projelendirme ve üretim süreci kusursuz ilerledi. Zamanında teslimat, net iletişim ve yüksek kalite standartları sayesinde hiçbir aksaklık yaşamadık. Gönül rahatlığıyla tavsiye ediyorum.",
  },
  {
    id: 4,
    person: "Carlos Rodríguez",
    role: "Grupo Hostelería Madrid (İspanya)",
    quote: "Endüstriyel mutfak ekipmanlarında uzun araştırmalar sonucunda Profinoks’u tercih ettik ve doğru karar verdiğimizi net şekilde gördük. Ürünlerin dayanıklılığı, hijyen standartlarına uygunluğu ve şık görünümü beklentimizin üzerindeydi. Ayrıca teknik ekip son derece bilgili ve işine hakim. Müşteri memnuniyetine gerçekten önem veriyorlar.",
  },
  {
    id: 5,
    person: "Ahmed Al Mansouri",
    role: "Al Noor Catering LLC (BAE)",
    quote: "Profinoks ile ilk çalışmamız olmasına rağmen süreç boyunca kendimizi güvende hissettik. İhtiyaç analizinden üretime kadar her aşamada şeffaf ve profesyonel bir yaklaşım sergilediler. Ürünler tam zamanında teslim edildi ve montaj sorunsuz tamamlandı. Uzun vadeli iş ortaklığı için kesinlikle tercih edilecek bir firma.",
  },
  {
    id: 6,
    person: "Omar Hassan",
    role: "Hassan Hospitality Group (Katar)",
    quote: "Kafe mutfağımız için aldığımız Profinoks ürünleri hem estetik hem de fonksiyonel açıdan beklentimizi fazlasıyla karşıladı. Günlük yoğun kullanımda bile ürünlerin sağlamlığı kendini net şekilde gösteriyor. Satış sonrası destek ekibine her ulaştığımızda hızlı ve çözüm odaklı geri dönüş aldık. Gerçek anlamda müşteri memnuniyeti odaklı çalışıyorlar.",
  },
  {
    id: 7,
    person: "Sophie Laurent",
    role: "Laurent Culinary Solutions (Belçika)",
    quote: "Profinoks’un profesyonelliği ilk görüşmeden itibaren hissediliyor. Proje sürecinde sundukları teknik bilgiler ve öneriler işimizi çok kolaylaştırdı. Ürünler yüksek kalite standartlarında üretildi ve mutfağımıza mükemmel uyum sağladı. Böyle bir hizmet anlayışına sahip firma bulmak günümüzde gerçekten zor, o yüzden çok memnunuz.",
  },
  {
    id: 8,
    person: "Michael Schneider",
    role: "Schneider Hotelbetrieb GmbH (Avusturya)",
    quote: "Yurtdışı projelerimizde de Profinoks ile çalıştık ve her aşamada aynı kaliteyi görmek bizi çok etkiledi. Ürünlerin uluslararası standartlara uygunluğu ve detaylara verilen önem gerçekten takdire şayan. Lojistik ve teslimat süreçleri de son derece profesyonel yönetildi. Güvenilir bir marka arayanlar için doğru adres.",
  },
  {
    id: 9,
    person: "Faisal Al Harbi",
    role: "Al Harbi Food Services (Suudi Arabistan)",
    quote: "Profinoks’un sunduğu çözümler sayesinde mutfak operasyonlarımız çok daha verimli hale geldi. Ürünler hem kullanım kolaylığı sağlıyor hem de uzun vadede maliyet avantajı sunuyor. Ekip son derece ilgili, ulaşılabilir ve çözüm odaklı. Bu yaklaşım, firmaya olan güvenimizi daha da artırdı.",
  },
  {
    id: 10,
    person: "Isabelle Martin",
    role: "Martin Catering & Events (Hollanda)",
    quote: "Profesyonel mutfak yatırımı yaparken en önemli kriterimiz kalite ve güvenilirlikti. Profinoks bu iki konuda da beklentimizin üzerinde bir performans sergiledi. Ürünlerin sağlamlığı, estetik duruşu ve satış sonrası destek hizmetleri gerçekten üst düzey. Bundan sonraki projelerimizde de ilk tercihimiz kesinlikle Profinoks olacak.",
  },
];

export const mainNavItems = [
  { label: "Home Page", path: "/", translationKey: "nav.home" },
  { label: "Corporate", path: "/corporate", translationKey: "nav.corporate" },
  { label: "Products", path: "/products", translationKey: "nav.products" },
  { label: "References", path: "/references", translationKey: "nav.references" },
  { label: "Projects", path: "/projects", translationKey: "nav.projects" },
  { label: "News", path: "/news", translationKey: "nav.news" },
  { label: "Contact", path: "/contact", translationKey: "nav.contact" },
];

export const projectImages = [
  "/profinoks/projects/1.jpg", "/profinoks/projects/2.jpg", "/profinoks/projects/3.jpg", "/profinoks/projects/4.jpg",
  "/profinoks/projects/5.jpg", "/profinoks/projects/6.jpg", "/profinoks/projects/7.jpg", "/profinoks/projects/8.jpg",
  "/profinoks/projects/9.jpg", "/profinoks/projects/10.jpg", "/profinoks/projects/11.jpg", "/profinoks/projects/12.jpg",
  "/profinoks/projects/14.jpeg", "/profinoks/projects/15.jpg", "/profinoks/projects/16.jpg", "/profinoks/projects/17.jpg",
  "/profinoks/projects/18.jpg", "/profinoks/projects/19.jpg", "/profinoks/projects/20.jpg", "/profinoks/projects/21.jpg",
  "/profinoks/projects/22.jpg", "/profinoks/projects/23.jpg", "/profinoks/projects/24.jpg", "/profinoks/projects/25.jpg",
  "/profinoks/projects/26.jpg", "/profinoks/projects/27.jpg", "/profinoks/projects/28.jpg", "/profinoks/projects/29.jpg",
  "/profinoks/projects/30.jpg", "/profinoks/projects/31.jpeg", "/profinoks/projects/32.jpg", "/profinoks/projects/33.jpg",
  "/profinoks/projects/34.jpg", "/profinoks/projects/35.jpg", "/profinoks/projects/36.jpg", "/profinoks/projects/37.jpg",
  "/profinoks/projects/38.jpg", "/profinoks/projects/39.jpg", "/profinoks/projects/40.jpg", "/profinoks/projects/41.jpg",
  "/profinoks/projects/42.jpg", "/profinoks/projects/43.jpg", "/profinoks/projects/44.jpg", "/profinoks/projects/45.jpg",
  "/profinoks/projects/46.jpg", "/profinoks/projects/47.jpg", "/profinoks/projects/48.jpg", "/profinoks/projects/49.jpg",
  "/profinoks/projects/50.jpg", "/profinoks/projects/51.jpg", "/profinoks/projects/52.jpg", "/profinoks/projects/53.jpg",
  "/profinoks/projects/54.jpg", "/profinoks/projects/55.jpg", "/profinoks/projects/56.jpg", "/profinoks/projects/57.jpg",
  "/profinoks/projects/58.jpg", "/profinoks/projects/59.jpg", "/profinoks/projects/60.jpg", "/profinoks/projects/61.jpg",
  "/profinoks/projects/62.jpg", "/profinoks/projects/63.jpg", "/profinoks/projects/64.jpeg", "/profinoks/projects/65.jpg",
  "/profinoks/projects/66.jpg", "/profinoks/projects/67.jpg", "/profinoks/projects/68.jpg", "/profinoks/projects/69.jpg",
  "/profinoks/projects/70.jpg", "/profinoks/projects/71.jpg", "/profinoks/projects/72.jpg", "/profinoks/projects/73.jpg",
  "/profinoks/projects/74.jpeg", "/profinoks/projects/75.jpg", "/profinoks/projects/76.jpg", "/profinoks/projects/77.jpg",
  "/profinoks/projects/78.jpg", "/profinoks/projects/79.jpg", "/profinoks/projects/80.jpg", "/profinoks/projects/81.jpg",
  "/profinoks/projects/82.jpg", "/profinoks/projects/83.jpg", "/profinoks/projects/84.jpg", "/profinoks/projects/85.JPG",
  "/profinoks/projects/86.jpg", "/profinoks/projects/87.jpg", "/profinoks/projects/88.jpg", "/profinoks/projects/89.jpg",
  "/profinoks/projects/90.jpg", "/profinoks/projects/91.jpg", "/profinoks/projects/92.jpg", "/profinoks/projects/93.jpg",
  "/profinoks/projects/94.jpg", "/profinoks/projects/95.jpg", "/profinoks/projects/96.jpg", "/profinoks/projects/97.jpg",
  "/profinoks/projects/98.jpg", "/profinoks/projects/99.jpg", "/profinoks/projects/100.jpg", "/profinoks/projects/101.jpg",
  "/profinoks/projects/102.jpg", "/profinoks/projects/103.jpg", "/profinoks/projects/104.jpg", "/profinoks/projects/105.JPEG",
  "/profinoks/projects/106.JPEG", "/profinoks/projects/107.jpg", "/profinoks/projects/108.jpg", "/profinoks/projects/109.jpg",
  "/profinoks/projects/110.jpg", "/profinoks/projects/111.jpg", "/profinoks/projects/112.jpg", "/profinoks/projects/113.jpg",
  "/profinoks/projects/114.jpg", "/profinoks/projects/115.jpg", "/profinoks/projects/116.jpg", "/profinoks/projects/117.jpg",
  "/profinoks/projects/118.jpg", "/profinoks/projects/120.jpg", "/profinoks/projects/121.jpg", "/profinoks/projects/122.jpg",
  "/profinoks/projects/123.jpg", "/profinoks/projects/124.jpg", "/profinoks/projects/125.jpg", "/profinoks/projects/126.jpg",
  "/profinoks/projects/127.jpg", "/profinoks/projects/128.jpg", "/profinoks/projects/129.jpg", "/profinoks/projects/130.jpg",
  "/profinoks/projects/131.jpg", "/profinoks/projects/132.jpg", "/profinoks/projects/133.jpg", "/profinoks/projects/134.jpg"
];
